2021-07-21 00:40:15,307 INFO    Thread-1474:29975 [wandb_setup.py:_flush():69] setting env: {'project': 'tess', 'entity': 'parsellsx', 'root_dir': '/home/parsellsx/berkeley-seti', 'run_id': 'nn0a244m', 'sweep_param_path': '/home/parsellsx/berkeley-seti/wandb/sweep-0b4ckdoq/config-nn0a244m.yaml', 'sweep_id': '0b4ckdoq'}
2021-07-21 00:40:15,307 INFO    Thread-1474:29975 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-21 00:40:15,307 INFO    Thread-1474:29975 [wandb_init.py:_log_setup():337] Logging user logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004015-nn0a244m/logs/debug.log
2021-07-21 00:40:15,308 INFO    Thread-1474:29975 [wandb_init.py:_log_setup():338] Logging internal logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004015-nn0a244m/logs/debug-internal.log
2021-07-21 00:40:15,308 INFO    Thread-1474:29975 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fed4924f3d0>
2021-07-21 00:40:15,308 INFO    Thread-1474:29975 [wandb_init.py:init():370] calling init triggers
2021-07-21 00:40:15,309 INFO    Thread-1474:29975 [wandb_init.py:init():377] wandb.init called with sweep_config: {'C': 0.001, 'gamma': 'scale', 'kernel': 'poly', 'tol': 0.01}
config: {}
2021-07-21 00:40:15,309 INFO    Thread-1474:29975 [wandb_init.py:init():419] starting backend
2021-07-21 00:40:15,309 INFO    Thread-1474:29975 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-21 00:40:15,312 INFO    Thread-1474:29975 [backend.py:ensure_launched():135] starting backend process...
2021-07-21 00:40:15,328 INFO    Thread-1474:29975 [backend.py:ensure_launched():140] started backend process with pid: 24079
2021-07-21 00:40:15,329 INFO    Thread-1474:29975 [wandb_init.py:init():424] backend started and connected
2021-07-21 00:40:15,362 INFO    Thread-1474:29975 [wandb_run.py:_config_callback():872] config_cb None None {'C': 0.001, 'gamma': 'scale', 'kernel': 'poly', 'tol': 0.01}
2021-07-21 00:40:15,363 INFO    Thread-1474:29975 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-21 00:40:15,363 INFO    Thread-1474:29975 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-07-21 00:40:15,363 INFO    Thread-1474:29975 [wandb_init.py:init():472] updated telemetry
2021-07-21 00:40:15,364 INFO    Thread-1474:29975 [wandb_init.py:init():491] communicating current version
2021-07-21 00:40:16,025 INFO    Thread-1474:29975 [wandb_init.py:init():496] got version response 
2021-07-21 00:40:16,025 INFO    Thread-1474:29975 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-21 00:40:16,207 INFO    Thread-1474:29975 [wandb_init.py:init():529] starting run threads in backend
2021-07-21 00:40:19,391 ERROR   Thread-1474:29975 [wandb_init.py:init():787] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 761, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 532, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 806, in communicate_run_start
    result = self._communicate(rec)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2021-07-21 00:44:06,842 INFO    MainThread:29975 [wandb_settings.py:_apply_source_login():716] setting login settings: {}
2021-07-21 00:44:06,847 INFO    MainThread:29975 [pyagent.py:run():321] Starting sweep agent: entity=None, project=None, count=None
2021-07-21 00:44:07,225 INFO    Thread-1478:29975 [wandb_setup.py:_flush():69] setting env: {'project': 'tess', 'entity': 'parsellsx', 'root_dir': '/home/parsellsx/berkeley-seti', 'sweep_id': '0b4ckdoq', 'run_id': 'd87jmsrw', 'sweep_param_path': '/home/parsellsx/berkeley-seti/wandb/sweep-0b4ckdoq/config-d87jmsrw.yaml'}
2021-07-21 00:44:07,225 INFO    Thread-1478:29975 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-21 00:44:07,225 INFO    Thread-1478:29975 [wandb_init.py:_log_setup():337] Logging user logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004407-d87jmsrw/logs/debug.log
2021-07-21 00:44:07,225 INFO    Thread-1478:29975 [wandb_init.py:_log_setup():338] Logging internal logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004407-d87jmsrw/logs/debug-internal.log
2021-07-21 00:44:07,226 INFO    Thread-1478:29975 [wandb_init.py:init():370] calling init triggers
2021-07-21 00:44:07,226 INFO    Thread-1478:29975 [wandb_init.py:init():377] wandb.init called with sweep_config: {'C': 0.001, 'gamma': 'scale', 'kernel': 'rbf', 'tol': 0.0001}
config: {}
2021-07-21 00:44:07,226 INFO    Thread-1478:29975 [wandb_init.py:init():419] starting backend
2021-07-21 00:44:07,226 INFO    Thread-1478:29975 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-21 00:44:07,229 INFO    Thread-1478:29975 [backend.py:ensure_launched():135] starting backend process...
2021-07-21 00:44:07,256 INFO    Thread-1478:29975 [backend.py:ensure_launched():140] started backend process with pid: 24132
2021-07-21 00:44:07,257 INFO    Thread-1478:29975 [wandb_init.py:init():424] backend started and connected
2021-07-21 00:44:07,289 INFO    Thread-1478:29975 [wandb_run.py:_config_callback():872] config_cb None None {'C': 0.001, 'gamma': 'scale', 'kernel': 'rbf', 'tol': 0.0001}
2021-07-21 00:44:07,289 INFO    Thread-1478:29975 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-21 00:44:07,290 INFO    Thread-1478:29975 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-07-21 00:44:07,290 INFO    Thread-1478:29975 [wandb_init.py:init():472] updated telemetry
2021-07-21 00:44:07,290 INFO    Thread-1478:29975 [wandb_init.py:init():491] communicating current version
2021-07-21 00:44:07,944 INFO    Thread-1478:29975 [wandb_init.py:init():496] got version response 
2021-07-21 00:44:07,944 INFO    Thread-1478:29975 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-21 00:44:08,048 INFO    Thread-1478:29975 [wandb_init.py:init():529] starting run threads in backend
2021-07-21 00:44:13,062 INFO    Thread-1478:29975 [wandb_run.py:_console_start():1623] atexit reg
2021-07-21 00:44:13,063 INFO    Thread-1478:29975 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2021-07-21 00:44:13,063 INFO    Thread-1478:29975 [wandb_run.py:_redirect():1534] Wrapping output streams.
2021-07-21 00:44:13,065 INFO    Thread-1478:29975 [wandb_run.py:_redirect():1558] Redirects installed.
2021-07-21 00:44:13,065 INFO    Thread-1478:29975 [wandb_init.py:init():554] run started, returning control to user process
2021-07-21 00:44:14,320 INFO    Thread-1478:29975 [wandb_run.py:finish():1293] finishing run parsellsx/tess/d87jmsrw
2021-07-21 00:44:14,321 INFO    Thread-1478:29975 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 1
2021-07-21 00:44:14,321 INFO    Thread-1478:29975 [wandb_run.py:_restore():1565] restore
2021-07-21 00:44:15,077 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 842
}

2021-07-21 00:44:16,055 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 842
  total_bytes: 842
}

2021-07-21 00:44:16,159 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 842
  total_bytes: 18473
}

2021-07-21 00:44:16,262 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:16,366 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:16,467 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:16,569 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:16,741 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:16,843 INFO    Thread-1478:29975 [wandb_run.py:_wait_for_finish():1715] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18473
  total_bytes: 18473
}

2021-07-21 00:44:18,049 INFO    Thread-1478:29975 [wandb_run.py:_show_files():1937] logging synced files
2021-07-21 00:44:18,061 ERROR   MainThread:29975 [pyagent.py:_run_jobs_from_queue():231] Run d87jmsrw errored: ValueError("pos_label=0 is not a valid label. It should be one of ['EB', 'Non-EB']")
2021-07-21 00:44:18,588 INFO    Thread-1487:29975 [wandb_setup.py:_flush():69] setting env: {'project': 'tess', 'entity': 'parsellsx', 'root_dir': '/home/parsellsx/berkeley-seti', 'run_id': 'nyu4zqp2', 'sweep_param_path': '/home/parsellsx/berkeley-seti/wandb/sweep-0b4ckdoq/config-nyu4zqp2.yaml', 'sweep_id': '0b4ckdoq'}
2021-07-21 00:44:18,588 INFO    Thread-1487:29975 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-21 00:44:18,588 INFO    Thread-1487:29975 [wandb_init.py:_log_setup():337] Logging user logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004418-nyu4zqp2/logs/debug.log
2021-07-21 00:44:18,588 INFO    Thread-1487:29975 [wandb_init.py:_log_setup():338] Logging internal logs to /home/parsellsx/berkeley-seti/wandb/run-20210721_004418-nyu4zqp2/logs/debug-internal.log
2021-07-21 00:44:18,589 INFO    Thread-1487:29975 [wandb_init.py:init():370] calling init triggers
2021-07-21 00:44:18,589 INFO    Thread-1487:29975 [wandb_init.py:init():377] wandb.init called with sweep_config: {'C': 0.001, 'gamma': 'scale', 'kernel': 'rbf', 'tol': 0.001}
config: {}
2021-07-21 00:44:18,589 INFO    Thread-1487:29975 [wandb_init.py:init():419] starting backend
2021-07-21 00:44:18,589 INFO    Thread-1487:29975 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-21 00:44:18,592 INFO    Thread-1487:29975 [backend.py:ensure_launched():135] starting backend process...
2021-07-21 00:44:18,611 INFO    Thread-1487:29975 [backend.py:ensure_launched():140] started backend process with pid: 24173
2021-07-21 00:44:18,612 INFO    Thread-1487:29975 [wandb_init.py:init():424] backend started and connected
2021-07-21 00:44:18,644 INFO    Thread-1487:29975 [wandb_run.py:_config_callback():872] config_cb None None {'C': 0.001, 'gamma': 'scale', 'kernel': 'rbf', 'tol': 0.001}
2021-07-21 00:44:18,645 INFO    Thread-1487:29975 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-21 00:44:18,645 INFO    Thread-1487:29975 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-07-21 00:44:18,645 INFO    Thread-1487:29975 [wandb_init.py:init():472] updated telemetry
2021-07-21 00:44:18,646 INFO    Thread-1487:29975 [wandb_init.py:init():491] communicating current version
2021-07-21 00:44:19,298 INFO    Thread-1487:29975 [wandb_init.py:init():496] got version response 
2021-07-21 00:44:19,298 INFO    Thread-1487:29975 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-21 00:44:19,399 INFO    Thread-1487:29975 [wandb_init.py:init():529] starting run threads in backend
2021-07-21 00:44:24,103 ERROR   Thread-1487:29975 [wandb_init.py:init():787] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 761, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 532, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 806, in communicate_run_start
    result = self._communicate(rec)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
